name: OpossumBot
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - krb5=1.20.1
  - libcxx=16.0.6
  - libedit=3.1.20230828
  - libexpat=2.5.0
  - libffi=3.4.2
  - libpq=12.17
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - mccabe=0.7.0
  - ncurses=6.4
  - openssl=3.1.4
  - pip=23.3.2
  - psycopg2-binary=2.9.9
  - python=3.11.6
  - readline=8.2
  - setuptools=69.0.3
  - tk=8.6.13
  - tzdata=2023d
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - aiohttp==3.9.2
      - aiosignal==1.3.1
      - argparse==1.4.0
      - astroid==3.0.2
      - attrs==23.2.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - dill==0.3.8
      - discord-py==2.3.2
      - docutils==0.20.1
      - frozenlist==1.4.1
      - idna==3.6
      - importlib-metadata==7.0.1
      - iniconfig==2.0.0
      - isort==5.13.2
      - jaraco-classes==3.3.1
      - keyring==24.3.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - multidict==6.0.4
      - nh3==0.2.15
      - packaging==23.2
      - pillow==10.2.0
      - pkginfo==1.9.6
      - platformdirs==4.1.0
      - pluggy==1.4.0
      - pygments==2.17.2
      - pylint==3.0.3
      - pytest==8.0.0
      - readme-renderer==42.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.7.0
      - tomlkit==0.12.3
      - twine==5.0.0
      - urllib3==1.26.18
      - yarl==1.9.4
      - zipp==3.17.0
