name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]


jobs:

  # We test before we end up adding the relevant token files & db.ini files
  test_and_push:

    runs-on: ubuntu-latest

    steps:
      # Diabled this step due to redundancy
      # - uses: actions/checkout@v4
      # - name: Build the Docker image (verify no issues)
      #   run: docker build . --file Dockerfile --tag opossumbot:$(date +%s)

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HOST_PRIVATEKEY }}
          known_hosts: 'placeholder'

    # Need to add the functionality of the database.ini and run.token
      - name: add database.ini
        run: |
          cd $GITHUB_WORKSPACE/
          touch database.ini
          echo "${{ secrets.DATABASE_INI }}" >> database.ini
      
      - name: add run.token
        run: |
          touch run.token
          echo ${{ secrets.DISCORD_TOKEN }} >> run.token

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
        run: rsync -avz $GITHUB_WORKSPACE ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }}:/home/opossumbot_run/runner/
        
        # TODO define this as an environment variable, to make removing it easier
        # remove container after stopping all running containers
        # Remove old alpha image from host
      - name: Remove old alpha image from host
        run: |
          ssh ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }} "fish docker rm (docker stop (docker ps -a -q))"
          ssh ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }} "docker rmi contrastellar/opossumbot:v3.alpha"


      # Needs to be updated on future builds
      - name: Build on host machine
        run: ssh ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }} "cd runner/OpossumBot_v3 && docker build . --tag contrastellar/opossumbot:v3.alpha"
      
      # Needs to be updated with future releases
      - name: Run new image
        run: ssh ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }} "docker start (docker create contrastellar/opossumbot:v3.alpha)"
