name: Build and Publish Docker Image

on:
  pull_request:
    branches: [ "main" ]


jobs:

  # We test before we end up adding the relevant token files & db.ini files
  test_and_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image (verify no issues)
        run: docker build . --file Dockerfile --tag opossumbot:$(date +%s)

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HOST_PRIVATEKEY }}
          known_hosts: 'placeholder'

    # Need to add the functionality of the database.ini and run.token
      - name: add database.ini
        run: |
          cd $GITHUB_WORKSPACE/
          touch database.ini
          echo ${{ secrets.DATABASE_INI }} >> database.ini
      
      - name: add run.token
        run: |
          touch run.token
          echo ${{ secrets.DISCORD_TOKEN }} >> run.token

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
        run: rsync -avz $GITHUB_WORKSPACE ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }}:/home/opossumbot_run/runner/

      - name: Build on host machine
        run: ssh ${{ secrets.HOST_USER }}@${{ secrets.SSH_HOST }} cd runner/OpossumBot_v3 && docker build . --tag opossumbot:$(date +%s)
