name: Build and Publish Docker Image

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "dev-actions" ]
jobs:

  # We test before we end up adding the relevant token files & db.ini files
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image (verify no issues)
        run: docker build . --file Dockerfile --tag opossumbot:$(date +%s)

  push_to_prod:
    name: Push to host
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HOST_PRIVATEKEY }}
          known_hosts: 'placeholder'
          
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
        run: rsync -avz $GITHUB_WORKSPACE ${{ secrets.HOST_USER }}@${{secrets.SSH_HOST }}:/home/opossumbot_run/runner/

      - name: Build on host machine
        run: ssh ${{ secrets.HOST_USER}}@${{ secrets.SSH_HOST }} cd runner && docker build . --tag opossumbot:$(date +%s)

      # more to be added later