# linting and testing script run
# this should only run on PRs to main

name: pytest-lint

on:
  push:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up conda /w python version ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3.0.2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        conda env create -f ./environment.yml -n test-env
        conda init
        conda activate test-env
        pip install -r requirements.txt
    - name: linting bot core /w pylint
      shell: bash -el {0}
      run: |
        conda activate test-env
        pylint --rcfile ./pylintrc.toml ./src/py/opossum_bot.py
    - name: linting functions /w pylint
      shell: bash -el {0}
      run: |
        conda activate test-env
        pylint --rcfile ./pylintrc.toml ./src/py/opossum_bot_functions/opossum_bot_functions.py
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.11.7"]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install --upgrade pytest
  #       pip install -r requirements.txt
  #   - name: testing /w pytest
  #     run: |
  #       pytest src/py/opossum_bot.py
  #       pytest src/py/opossum_bot_functions/opossum_bot_functions.py
  